---
- name: Yggdrasil Pre-Check
  hosts: localhost
  vars_prompt:
    - name: setup_questions
      prompt: 'What Hypervisor are you using'

  pre_tasks:
    - name: Make sure ansible is at least version 2.10 or greater
      ansible.builtin.assert:
        that:
          - ansible_version.full is version('2.10.0', '>=')
        quiet: true
        fail_msg: "You must update Ansible to at least 2.10.0 to use this role.\n"

  tasks:
    - name: set vars_prompt as persistent fact
      ansible.builtin.lineinfile:
        path: /path/to/file
        line: 'test'
        regexp: '^test$'
