---
- name: Update and upgrade Ubuntu
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: inventory_host in groups.anisble_controller

- name: Install Hashicorp GPG Key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Install needed dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - terraform
    - vault
    - packer
    - kubernetes

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/x-Notorious/dotfiles
    dest: ~/.dotfiles
    version: master
  become: false
