---
- name: Update Package cache (apt/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  when: ansible_distribution == "Debian"

- name: Update Package cache (dnf/RHEL)
  ansible.builtin.dnf:
    update_cache: true
    name: '*'
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Update Package cache (pacman/Arch)
  community.general.pacman:
    update_cache: true
  changed_when: false
  when: ansible_os_family == "Archlinux"

- name: Install needed dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - terraform
    - vault
    - packer
    - docker
    - kubernetes
    - vagrant

- name: Download ProxMox ISO image
  ansible.builtin.get_url:
    url: "{{ proxmox_download }}"
    dest: ~/iso_images
    mode: '0600'
